[package]
org = "demo"
name = "order_mgt"
version = "0.1.0"
distribution = "2201.9.0-20240425-195200-d5ce8c72"

[build-options]
observabilityIncluded = true

[[tool.persist]]
id = "generate-db-client"
targetModule = "order_mgt.db"
options.datastore = "mysql"
filePath = "persist/model.bal"

[[platform.java17.repository]]
id="wso2-nexus-snapshot"
url = "https://maven.wso2.org/nexus/content/repositories/snapshots/"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.3.0-SNAPSHOT"

